# -*- coding: utf-8 -*-
"""Creating Jira issue using REST API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7-ZwuRNw0wlrMfkwUCoDq6Z1r-dvk-Y
"""

import requests
from requests.auth import HTTPBasicAuth

# Jira account and API endpoint details
JIRA_URL = 'https://xyz.atlassian.net/'  # Replace with your Jira URL
JIRA_API_ENDPOINT = 'https://xyz.atlassian.net/rest/api/2/issue'  # Replace with your Jira API endpoint
JIRA_USER = 'xyz@gmail.com'  # Replace with your Jira username
JIRA_API_TOKEN = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'  # Your API token

# Function to create a Jira issue
def create_jira_issue(project_key, issue_type, summary, description):
    headers = {
        'Content-Type': 'application/json'
    }
    auth = HTTPBasicAuth(JIRA_USER, JIRA_API_TOKEN)

    # Data for the Jira issue
    data = {
    "fields": {
        "project": {
            "key": project_key
        },
        "summary": summary,
        "description": description,
        "issuetype": {
            "name": issue_type
        },
        "assignee": {
            "name": "baldeep.singh@XYZ.com"  # Replace with the username of the person you're assigning to
        }
    }
}


    # Send POST request to create the issue
    response = requests.post(JIRA_API_ENDPOINT, json=data, headers=headers, auth=auth)

    if response.status_code == 201:
        print("Issue created successfully.")
        print("Issue URL:", response.json().get('self'))
    else:
        print("Failed to create issue.")
        print("Response:", response.text)

# Main function
def main():
    # Specify the project key, issue type, summary, and description
    project_key = 'PROJECT_KEY'  # Replace with your project key
    issue_type = 'Task'  # Issue type such as Task, Bug, etc.
    summary = 'Baldeep Test OKOK'
    description = 'This is Baldeep test Description OKOK Test'

    # Create the Jira issue
    create_jira_issue(project_key, issue_type, summary, description)

if __name__ == '__main__':
    main()